[directories]
maps = "/maps"
data = "/gameData"
battlePics = "/generated/trainers"
sprites = "/generated/trainers/48"
output = "/generated"
miscScripts = "/_scripts"

[scriptNamesToLevels]
PLAYERSHOUSE = "LITTLEROOT_TOWN"
CONTESTHALL = "LILYCOVE_CITY"
