[directories]
maps = "/maps"
data = "/gameData"
sprites = "/graphics"
output = "/generated"
miscScripts = "/_scripts"

[scriptNamesToLevels]
PLAYERSHOUSE = "LITTLEROOT_TOWN"
CONTESTHALL = "LILYCOVE_CITY"
